spring:
  #cache:
    #type: ehcache
    #ehcache:
      #config: classpath:ehcache.xml
  #activiti:
    #check-process-definitions: true
    #database-schema-update: true
    #这里保存全部历史记录
    #history-level: full
  application:
    name: tetris-capacity
  cloud:
#    config:
#      uri: http://192.165.56.71:8081
#      fail-fast: true
    client:
      ipAddress: 10.10.40.24
#  profiles:
#    active: pro
  datasource:
    base:
      url: jdbc:mysql://localhost:3306/capacity?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
      username: root
      password: sumavisionrd
      driver-class-name: com.mysql.jdbc.Driver
      initial-size : 10
      min-idle : 20
      max-active : 100
      validation-query : SELECT 1
      test-while-idle : true
      test-on-borrow : true
      time-between-eviction-runs-millis : 600000
      min-evictable-idle-time-millis : 3600000
#    resource:
#      url: jdbc:mysql://localhost:3306/venus_resource?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&&useSSL=true
#      username: root
#      password: sumavisionrd
#      driver-class-name: com.mysql.jdbc.Driver
#      initial-size : 10
#      min-idle : 20
#      max-active : 100
#      validation-query : SELECT 1
#      test-while-idle : true
#      test-on-borrow : true
#      time-between-eviction-runs-millis : 600000
#      min-evictable-idle-time-millis : 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    
  #spring mvc视图
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #http文件上传    
  http: 
    multipart:
      enabled: true   
  #Redis配置信息
#  redis:
#    #Redis数据库索引（默认为0）  
#    database: 0
#    #Redis服务器地址  
#    host: 192.165.56.84 
#    port: 6379
#    password: sumavisionrd
#    #连接池最大阻塞等待时间(使用负值表示没有限制)
#    max-wait: 30000
#    #连接池最大连接数(使用负值表示没有限制)
#    max-active: 100
#    #连接池中的最大空闲连接
#    max-idle: 20
#    #连接池中的最小空闲连接
#    min-idle: 0
#    #连接超时
#    timeout: 3000
server:
#  context-path: /menu 
#  address: 192.165.56.71
  port: 8092
  max-http-header-size: 10485760 #spring feign用了get请求，参数写在了url上，导致长度受限8K
logging:
  pattern:
    console: "%d - %msg%n"
    level: INFO
  path: /var/log/tomcat
ribbon:
  eager-load:
      enabled: true
      clients: tetris-menu
  ReadTimeout: 120000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.40.184:8081/eureka/
#      defaultZone: http://192.165.58.123:8081/eureka/
#      defaultZone: http://192.165.56.16:8081/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 10.10.40.24
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2
#security:
#  oauth2:
#    resource:
      #指定resource的唯一标识
#      id: ${spring.application.name}
      #是否使用token info
#      prefer-token-info: false
      #指定user info的URI
#      user-info-uri: http://192.165.56.64:5000/uaa/users/current
feign: 
  hystrix: 
   enabled: true    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread: 
            timeoutInMilliseconds: 5000
          strategy: SEMAPHORE  
log:
  home: /usr/sbin/sumavision/tetris/tetris-project/capacity/apache-tomcat-7.0.93/logs
  maxFileSize: 30MB
  maxHistory: 10
  totalSizeCap: 1GB
constant:
  default:
    video:
      encode: m2v
      resolution: 720x576
      fps: -1
    audio:
      encode: mp2
#      打开音柱
      column: 1