server:
  port: 8090

spring:
  application:
    name: tetris-record
  cloud:
    client:
      ipAddress: 10.10.40.27
    inetutils:
      preferred-networks: 10.10.40.27

  datasource:
      url: jdbc:mysql://10.10.40.104:3306/record?characterEncoding=utf-8&useUnicode=true&&useSSL=false
      username: root
      password: sumavisionrd
      driver-class-name: com.mysql.jdbc.Driver
      driverClassName: com.mysql.jdbc.Driver
      druid:
        initial-size: 10
        min-idle: 20
        max-active: 100
        validation-query : SELECT 1
        test-while-idle : true
        time-between-eviction-runs-millis : 600000
        min-evictable-idle-time-millis : 3600000
    
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
    preferIpAddress: true
    ipAddress: 10.10.40.27
    instance-id: ${eureka.instance.ipAddress}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone:  http://10.10.40.104:8081/eureka/
ribbon:
  eager-load:
      enabled: true
      clients: tetris-user
  ReadTimeout: 120000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 3
feign: 
  hystrix: 
   enabled: true    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread: 
            timeoutInMilliseconds: 5000
          strategy: SEMAPHORE
localRecordBasePath: /home/record/
localFFMpegOutputPath: /home/output/
ftpBasePath: ftp://suma:suma123@10.10.40.104/
httpBasePath: http://10.10.40.104:9081/record/
clean_diskUsedPercentThreshold: 78
clean_recordMaxSpaceThreshold: 10
clean_timeThreshold: 30
taskTemplateName: RECORD_COMMON


