spring:
  application:
    name: suma-bvc-business-zsy
  cloud:
#    config:
#      uri: http://localhost:8769
#      fail-fast: true
    client:
      ipAddress: 192.165.56.77
  profiles:
    active: pro
  datasource:
    base:
      url: jdbc:mysql://localhost:3306/sgdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
      username: root
      password: sumavisionrd
#      url: jdbc:mysql://192.165.56.140:3306/bvc_business?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
#      username: sumadb
#      password: Sumavision@300079
      driver-class-name: com.mysql.jdbc.Driver
      initial-size : 10
      min-idle : 20
      max-active : 100
      validation-query : SELECT 1
      test-while-idle : true
      test-on-borrow : true
      time-between-eviction-runs-millis : 600000
      min-evictable-idle-time-millis : 3600000
    resource:
      url: jdbc:mysql://192.165.56.84:3306/venus_resource?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&&useSSL=false
      username: root
      password: sumavisionrd
#      username: sumadb
#      password: Sumavision@300079
      driver-class-name: com.mysql.jdbc.Driver
      initial-size : 10
      min-idle : 20
      max-active : 100
      validation-query : SELECT 1
      test-while-idle : true
      test-on-borrow : true
      time-between-eviction-runs-millis : 600000
      min-evictable-idle-time-millis : 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    
  #spring mvc视图
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8085
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.165.56.84:8081/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    prefer-ip-address: true
security:
  oauth2:
    resource:
      #指定resource的唯一标识
      id: ${spring.application.name}
      #是否使用token info
      prefer-token-info: false
      #指定user info的URI
      user-info-uri: http://192.165.56.84:8881/uaa/users/current
    