server:
  port: 8081

eureka:
  instance:
    hostname: 192.165.56.23
  # 关闭自我保护机制，保证不可用服务及时踢出
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: tetris-spring-eureka
