spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: tetris-scl
  cloud:
#    config:
#      uri: http://localhost:8769
#      fail-fast: true
    client:
      ipAddress: 192.165.56.64
  profiles:
    active: pro
  datasource:
    base:
     
      url: jdbc:mysql://localhost:3306/scl?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: sumavisionrd
#      username: sumadb
#      password: Sumavision@300079
      driver-class-name: com.mysql.jdbc.Driver
      initial-size : 10
      min-idle : 20
      max-active : 100
      validation-query : SELECT 1
      test-while-idle : true
      test-on-borrow : true
      time-between-eviction-runs-millis : 600000
      min-evictable-idle-time-millis : 3600000
    resource:
   
      url: jdbc:mysql://192.165.56.131:3306/resource?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
      username: sumadb
      password: Sumavision@300079
      driver-class-name: com.mysql.jdbc.Driver
      initial-size : 10
      min-idle : 20
      max-active : 100
      validation-query : SELECT 1
      test-while-idle : true
      test-on-borrow : true
      time-between-eviction-runs-millis : 600000
      min-evictable-idle-time-millis : 3600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  #Redis配置信息
  redis:
    #Redis数据库索引（默认为0）  
    database: 15
    #Redis服务器地址  
    host: 192.165.56.84 
    port: 6379
    password: sumavisionrd
    #连接池最大阻塞等待时间(使用负值表示没有限制)
    max-wait: 30000
    #连接池最大连接数(使用负值表示没有限制)
    max-active: 100
    #连接池中的最大空闲连接
    max-idle: 20
    #连接池中的最小空闲连接
    min-idle: 0
    #连接超时
    timeout: 3000
    
  #spring mvc视图
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8095
logging:
  pattern:
    console: "%d - %msg%n" 
    level: INFO 
  path: /var/log/tomcat 
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
eureka:
  client:
    serviceUrl:

      defaultZone: http://192.165.56.131:8081/eureka/
#      defaultZone: http://192.165.56.16:8081/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    prefer-ip-address: true
socket:
  port: 9999
constant:
  message:
    mode: 1
  package:
    output:
      type: srt
